[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "brewcli"
version = "0.1.0"
readme = "README.md"
authors = [{ name = "Tyler Nardone", email = "tynardone@gmail.com" }]

[tool.ruff.lint]
extend-select = ["E501"]


[tool.pylint."messages control"]
disable = ["R0902", "R0903", "C0115", "C0114", "E1101"]
